PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: sqlite
    database: examples/yahpo/yahpo
    table:
      name: yahpo_runs
      keyfields:
        scenario:
          type: VARCHAR(255)
        dataset:
          type: VARCHAR(255)
        seed:
          type: INT
        n_trials:
          type: INT
      result_timestamps: False
      resultfields:
        final_cost: FLOAT
        runtime: FLOAT
